Nie
ManasMods/reincarnated_mod pull request #461
Opened 2022-08-08 20:52 UTC by Nieadni

Updated lang file, added temp textures for most items, added entries for most weapons, started to implement giant salmon, and im probably forgetting something else.

2022-08-09 08:43 UTC, Charismara requested changes

2022-08-09 08:43 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/Tensura.java
> +    public static final Logger LOGGER = LogManager.getLogger();
Keep the logger field private and use the getter method

2022-08-11 19:34 UTC, Nieadni commented
Le merge?

2022-08-11 20:24 UTC, Charismara requested changes
43 new things to change. lol

2022-08-11 20:24 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/registry/SkillRegistry.java
> +public class SkillRegistry {
make class only accessable for the package

2022-08-11 20:24 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/registry/SkillRegistry.java
> +    public static final ResourceLocation SKILLS_REGISTRY_NAME = new ResourceLocation(Tensura.MOD_ID, "skills");
make field only accessable for the package and rename field to REGISTRY_KEY

2022-08-11 20:24 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/registry/SkillRegistry.java
> +    private static final DeferredRegister<Skill> skillRegister = DeferredRegister.create(SKILLS_REGISTRY_NAME, Tensura.MOD_ID);
Move this to TensuraRegistry

2022-08-11 20:24 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/registry/SkillRegistry.java
> +        skillRegister.makeRegistry(Skill.class, RegistryBuilder::new);
move this to a public static final field in TensuraRegistry

2022-08-11 20:24 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/registry/SkillRegistry.java
> +        skillRegister.register(eventBus);
Do this in TensuraRegistry.register

2022-08-11 20:24 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/registry/TensuraRegistry.java
> -    public static final Supplier<IForgeRegistry<Race>> RACE_REGISTRY = RACES.makeRegistry(Race.class, RegistryBuilder::new);
Why removing that stuff?

2022-08-11 20:24 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/registry/TensuraRegistry.java
> -        RaceRegistry.register(RACES);
Why removing that stuff?

2022-08-11 20:24 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/registry/TensuraRegistry.java
> -        RACES.register(modEventBus);
Why removing that stuff?

2022-08-11 20:24 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/skills/Skill.java
> +    }
Remove this and add `@Getter` to the field

2022-08-11 20:24 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/skills/capability/ISkillCapability.java
> +    public static final ResourceLocation IDENTIFIER = new ResourceLocation(Tensura.MOD_ID, "skillscap");
Move static fields to interface implementation

2022-08-11 20:24 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/skills/capability/SkillCapability.java
> +    private CompoundTag savedData;
Unused Field?

2022-08-11 20:24 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/skills/capability/SkillCapabilityProvider.java
> +public class SkillCapabilityProvider implements ICapabilityProvider, INBTSerializable<CompoundTag> {
implement `ICapabilitySerializable<CompoundTag>` instead of `INBTSerializable<CompoundTag>`

2022-08-11 20:24 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/skills/targetselectors/TargetSelector.java
> +    public void apply(Level level, R entity);
Is R always an entity?

2022-08-11 20:24 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/skills/targetselectors/TargetSelectorExecutor.java
> +    public void execute(Level level, SkillInstance instance, R r);
What is R?

2022-08-11 20:24 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/world/ModWorldEvents.java
> +public class ModWorldEvents {
Rename to EntityHandler

2022-08-11 20:24 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/world/ModWorldEvents.java
> +package com.github.manasmods.tensura.world;
Move to `com.github.manasmods.tensura.handler`

2022-08-11 20:24 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/world/entity/ModEntityGeneration.java
> +    }
Why don't subscripe to the event here?

2022-08-11 20:24 UTC, Charismara commented on src/test/java/com/github/manasmods/tensura/TestBatches.java
> -    public static final String ATTRIBUTE_TESTS = "attribute_tests";
Why removing the field?

2022-08-11 20:24 UTC, Charismara commented on src/test/java/com/github/manasmods/tensura/SkillCapabilityTest.java
> +        capability.acquireSkill(skill);
This is not how we should work with capabilities.
1. Apply them in `AttachCapabilitiesEvent`
2. Create static methods to get and sync the capability

2022-08-12 19:57 UTC, Nieadni commented on src/main/java/com/github/manasmods/tensura/Tensura.java
> -        PlayerLogInHandler.register(forgeEventBus);
idk

2022-08-12 20:43 UTC, Nieadni commented on src/test/java/com/github/manasmods/tensura/SkillCapabilityTest.java
> +        capability.acquireSkill(skill);
This was something I got from Nights branch lol

2022-08-13 08:51 UTC, Charismara commented
Your whole branch is fcked up. I can't merge it.

Restore a working state please

2022-08-13 13:26 UTC, closed without merging