Dev/nieadni
ManasMods/reincarnated_mod pull request #486
Opened 2022-08-18 20:43 UTC by Nieadni

2022-08-19 13:56 UTC, Charismara requested changes

2022-08-19 13:56 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/registry/ItemRegistry.java
> -        registry.register("winged_boots", () -> new SimpleBootsItem(TensuraArmourMaterials.WINGED_BOOTS));
U remove the boots?

2022-08-19 20:01 UTC, Nieadni commented on src/main/java/com/github/manasmods/tensura/registry/ItemRegistry.java
> -        registry.register("winged_boots", () -> new SimpleBootsItem(TensuraArmourMaterials.WINGED_BOOTS));
Yeah. Some lore stuff. Basically they are just normal boots imbued with magic and we plan to have that system so it was pointless

2022-08-20 08:40 UTC, Charismara approved these changes

2022-08-20 08:40 UTC, merged