Dev/nightishaman
ManasMods/reincarnated_mod pull request #494
Opened 2022-08-20 23:44 UTC by maltesermailo

2022-08-21 08:30 UTC, Charismara requested changes

2022-08-21 08:30 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/skills/capability/ISkillCapability.java
> +    public static final ResourceLocation IDENTIFIER = new ResourceLocation(Tensura.MOD_ID, "skillscap");
we don't want to make those accessable to others. move those to the cap implementation and make them private or package

2022-08-21 08:30 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/skills/capability/SkillCapability.java
> +    }
why are you storing a player object?

2022-08-21 08:30 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/skills/capability/SkillCapability.java
> +
maybe add static attach, sync and getter here

2022-08-21 08:30 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/skills/capability/SkillCapability.java
> +        tag.put("skills", skillList);
registry objects are always the same on Server and all client instances. You don't need to store them (except their registry name)? Do u?

2022-08-21 08:30 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/skills/capability/SkillCapability.java
> +        }
why don't u use for each here?

2022-08-21 08:30 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/skills/capability/SkillCapabilityProvider.java
> +public class SkillCapabilityProvider implements ICapabilityProvider, INBTSerializable<CompoundTag> {
use `ICapabilitySerializable<CompoundTag>` instead of `ICapabilityProvider, INBTSerializable<CompoundTag>`

2022-08-21 08:30 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/skills/common/SelfRegenerationSkill.java
> +    }
what are you doing here?

2022-08-21 08:30 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/skills/targetselectors/ClientTargetSelector.java
> +}
why do we need a client selector? Wouldn't that allow clients to manipulate data?

2022-08-21 08:30 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/network/SkillMessage.java
> +}
why don't u use packets in a common way?

2022-08-21 08:30 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/network/event/PacketReceivedEvent.java
> +}
why don't u use packets in a common way?

2022-08-21 08:30 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/skills/targetselectors/TargetSelector.java
> +}
u might wanna make a new registry type for target selectors. It seems like we want them to always be the same on all mod instances

2022-08-22 19:56 UTC, maltesermailo commented on src/main/java/com/github/manasmods/tensura/skills/Skill.java
> +    }
Its more like a load skill from name method, yet used during deserialization of the skill capability hence its name

2022-08-22 19:57 UTC, maltesermailo commented on src/main/java/com/github/manasmods/tensura/skills/SkillInstance.java
> +    private CompoundTag data;
Deleted

2022-08-22 19:57 UTC, maltesermailo commented on src/main/java/com/github/manasmods/tensura/skills/SkillInstance.java
> +
Added @Getter to a variable

2022-08-22 20:00 UTC, maltesermailo commented on src/main/java/com/github/manasmods/tensura/skills/capability/SkillCapability.java
> +    }
Mainly for identification in TargetSelectorExecutors

2022-08-22 20:03 UTC, maltesermailo commented on src/main/java/com/github/manasmods/tensura/skills/capability/SkillCapability.java
> +        }
because Maps can't be modified while iterated with foreach. ConcurrentModificationException. Iterator avoids this.

2022-08-22 20:05 UTC, maltesermailo commented on src/main/java/com/github/manasmods/tensura/network/SkillMessage.java
> +}
because then i would have to handle a list of all targetselectors who want to be notified when the packet comes. mainly this is for the client to send skill used on key and the server to handle the logic then

2022-08-22 20:05 UTC, maltesermailo commented on src/main/java/com/github/manasmods/tensura/skills/common/SelfRegenerationSkill.java
> +    }
Testing storage data, has been update

2022-08-22 23:05 UTC, Charismara requested changes

2022-08-22 23:05 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/registry/TensuraRegistry.java
> +    public static final DeferredRegister<Race> RACES = DeferredRegister.create(RaceRegistry.REGISTRY_KEY, Tensura.MOD_ID);
Please make them private again. We don't want others to access our `DeferredRegister` objects

2022-08-22 23:05 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/data/TensuraEntityLoot.java
> +        return TensuraRegistry.ENTITY_TYPES.getEntries().stream().map(RegistryObject::get).collect(Collectors.toList());
add a getter for this in TensuraRegistry instead

2022-08-22 23:05 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/data/TensuraBlockLoot.java
> +        return TensuraRegistry.BLOCKS.getEntries().stream().map(RegistryObject::get)::iterator;
add a getter for this in TensuraRegistry instead

2022-08-22 23:17 UTC, maltesermailo commented on src/main/java/com/github/manasmods/tensura/registry/TensuraRegistry.java
> +    public static final Supplier<IForgeRegistry<Skill>> SKILL_REGISTRY_BUILDER = SKILL.makeRegistry(Skill.class, RegistryBuilder::new);
Only used for custom registries to fill the forge registry held in this DeferredRegister. Calls RegistryBuilder.setName and RegistryBuilder.setType automatically.
Params:
base – The base type to use in the created IForgeRegistry sup – Supplier of a RegistryBuilder that initializes a IForgeRegistry during the NewRegistryEvent event
Returns:
A supplier of the IForgeRegistry created by the builder. Will always return null until after the NewRegistryEvent event fires.

2022-08-22 23:17 UTC, maltesermailo commented on src/main/java/com/github/manasmods/tensura/registry/TensuraRegistry.java
> +    public static final Supplier<IForgeRegistry<Skill>> SKILL_REGISTRY_BUILDER = SKILL.makeRegistry(Skill.class, RegistryBuilder::new);
Thereby, using that supplier is not possible

2022-08-22 23:33 UTC, maltesermailo commented on src/main/java/com/github/manasmods/tensura/registry/TensuraRegistry.java
> +    public static final DeferredRegister<Skill> SKILL = DeferredRegister.create(SkillRegistry.REGISTRY_KEY, Tensura.MOD_ID);
Thing is, the disabled skills are placed in the same list as the enabled one, they just dont have the boolean instance set to true.

2022-08-23 08:49 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/registry/TensuraRegistry.java
> +    public static final DeferredRegister<Skill> SKILL = DeferredRegister.create(SkillRegistry.REGISTRY_KEY, Tensura.MOD_ID);
i kinda don't get why we should make our `DeferredRegister` public? We don't want others to access our stuff though our `DeferredRegister`. Everyone should use the RegistryObject instead

2022-08-23 20:43 UTC, maltesermailo commented on src/main/java/com/github/manasmods/tensura/registry/TensuraRegistry.java
> +    public static final DeferredRegister<Skill> SKILL = DeferredRegister.create(SkillRegistry.REGISTRY_KEY, Tensura.MOD_ID);
Cap owner is the stored player, yes.

2022-08-23 21:01 UTC, maltesermailo commented on src/main/java/com/github/manasmods/tensura/skills/capability/SkillCapability.java
> +        }
Well, that concurrentmodificationexception is with lists and i used a list while testing before i switched to a map. anyway, i dont see a reason not to use an iterator. same thing as using a foreach but looks cleaner

2022-08-23 21:02 UTC, maltesermailo commented on src/main/java/com/github/manasmods/tensura/skills/capability/SkillCapability.java
> +        tag.put("skills", skillList);
yeah but they are saved with the enabled skills(only difference is that enabled skills have instance set to 1 in that sub nbt tag)

2022-08-29 18:01 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/core/MixinBlockLoot.java
> +public abstract class MixinBlockLoot {
bitte ein interface draus machen :)

2022-08-29 18:03 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/core/MixinBlockLoot.java
> +    }
einen methoden body brauchen wir in einem Interface nicht.
Ich glaube du kann auch das Target in der Annotation auswählen und den Methodennamen selbst bestimmen.

2022-08-29 18:11 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/skills/Skill.java
> +    }
die ResourceLocation kann aus dem Constructor raus. Forge setzt mit dem Setter die RegistryLocation

2022-08-30 08:54 UTC, Charismara requested changes

2022-08-30 08:54 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/core/MixinBlockLoot.java
> +    }
Gib hier dann am Besten einen `AssertionError` zurück und keinen leeren wert

2022-09-03 15:05 UTC, Charismara approved these changes

2022-09-03 15:05 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/skills/capability/SkillCapability.java
> +        tag.put("skills", skillList);
A SkillInstance know about their "parent" skill don't they? Couldn'u you just add a boolean to the SkillInstance to check if the skill is enabled or not and remove the whole `skills` map?

2022-09-03 15:07 UTC, Charismara requested changes
still some conversations open

2022-09-03 15:43 UTC, maltesermailo commented on src/main/java/com/github/manasmods/tensura/skills/SkillEffectInstance.java
> +    private TargetSelector clientTargetSelector;
SkillEffect provides suppliers creating the target selector, SkillEffectInstance stores the actual targetselector to be able to unregister it

2022-09-03 18:46 UTC, maltesermailo commented on src/main/java/com/github/manasmods/tensura/skills/capability/SkillCapability.java
> +        tag.put("skills", skillList);
because some skills can be found standalone while also being on another skill as a parent(ex: common skill on a unique skill), therefore i save every skill extra. the skills map is still needed tho since skills have to be saved.

2022-09-04 11:30 UTC, Charismara approved these changes

2022-09-04 11:31 UTC, Charismara commented
CI/CD is failing. please fix that issue

2022-09-18 12:22 UTC, Charismara approved these changes

2022-09-18 12:23 UTC, Charismara approved these changes

2022-09-18 12:24 UTC, merged