Feel empty and bored so I fixed some stuffs
ManasMods/reincarnated_mod pull request #495
Opened 2022-08-21 13:22 UTC by minheragon12345

2022-08-21 19:22 UTC, Charismara requested changes

2022-08-21 19:22 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/block/SimpleBlock.java
> +    }
block will drop what their loot table say, not themself. remove that please

2022-08-21 19:22 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/block/SmithingBenchBlock.java
> +            return null;
don't return null here, return the default blockstate

2022-08-21 22:29 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/block/SimpleBlock.java
> +    }
But not all blocks have lootable, they just drop themselves

2022-08-21 22:41 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/block/SmithingBenchBlock.java
> +            return null;
Oh Nah, it's me forgetting the @Nullable like how Loom block is.
What I'm doing is check if it's "placeable", if the block on the left is replaceable to put the anvil there, if not, it will just not let u place the block, I'm afraid that return default will still place the block

2022-08-21 22:50 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/block/SimpleBlock.java
> +    }
So we will have to add lootables for every block...

2022-08-22 19:54 UTC, Charismara requested changes

2022-08-22 19:54 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/block/SimpleBlock.java
> +    }
Don't override that method. Use Loot Tables

2022-08-22 19:55 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/block/SimpleBlock.java
> +    }
yes

2022-08-22 21:43 UTC, Nieadni commented on src/main/java/com/github/manasmods/tensura/block/SimpleBlock.java
> +    }
I do this in my pull request. You can just remove this

2022-08-22 22:22 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/block/SimpleBlock.java
> +    }
we gonna wait for a merge of #497 and then update this branch

2022-08-22 22:57 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/block/SimpleBlock.java
> +    }
Oh wut, u're looking at the old codes, check out the 
![image](https://user-images.githubusercontent.com/29400456/186033052-99881a92-537d-4e21-afb2-f01fe41dd4b8.png)
 I have already removed it

2022-08-23 09:02 UTC, Charismara approved these changes

2022-08-23 09:03 UTC, merged