Got custom screen and logo to work and updated lang file
ManasMods/reincarnated_mod pull request #498
Opened 2022-08-22 23:07 UTC by Nieadni

[Got custom screen and logo to work and updated lang file](https://github.com/ManasMods/reincarnated_mod/commit/585beac1bb6e5fc6600eafda8d7ea5f853f5df2a)

2022-08-23 09:00 UTC, Charismara requested changes
last review for the next week

2022-08-23 09:00 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/event/TensuraEvents.java
> +            event.setScreen(new TensuraTitleScreen());
what are u trying to achive? Why are u replacing the whole title screen

2022-08-23 11:39 UTC, Nieadni commented on src/main/java/com/github/manasmods/tensura/event/TensuraEvents.java
> +            event.setScreen(new TensuraTitleScreen());
More proof of concept. We may aswell have a custom title screen for release so I was just testing it

2022-08-23 11:44 UTC, Nieadni commented on src/main/java/com/github/manasmods/tensura/event/TensuraEvents.java
> +    }
done

2022-08-23 11:45 UTC, Nieadni commented
> last review for the next week

Bruh. Its only tuesday

2022-08-24 13:21 UTC, Nieadni commented
┬┴┬┴┤(･_├┬┴┬┴

2022-08-30 08:57 UTC, Charismara requested changes

2022-08-30 08:57 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/client/TensuraClient.java
> +    }
Add the listener in `Tensura` using a DistExecutor

2022-09-03 14:32 UTC, Charismara requested changes

2022-09-03 14:32 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/Tensura.java
> +        forgeEventBus.addListener(TensuraClient::openGui);
Please use a DistExecutor to only add that listener on client side

2022-09-03 15:40 UTC, Charismara approved these changes

2022-09-03 15:40 UTC, merged