Wooden stuffs and Ice blade
ManasMods/reincarnated_mod pull request #503
Opened 2022-08-24 09:07 UTC by minheragon12345

2022-08-30 09:14 UTC, Charismara requested changes

2022-08-30 09:14 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/handler/HurtEventHandler.java
> +    }
move this into the `TensuraEntityHandler` class and remove the `HurtEventHandler`

2022-08-30 09:14 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/handler/TensuraArmourHandler.java
> +        }
do this in `TensuraClient`

2022-08-30 09:14 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/registry/ItemRegistry.java
> +                .fireResistant()));
don't set the ItemProperties in the registry class. Do it in the `IceBladeItem` class

2022-08-30 09:14 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/custom/IceBladeItem.java
> +        super(pTier, pAttackDamageModifier, pAttackSpeedModifier, pProperties);
set the Item.Properties in the super statement and remove it from the constructor params

2022-08-30 09:14 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/registry/TensuraEntityTypes.java
> +    public static RegistryObject<EntityType> BOAT_ENTITY, GIANT_SALMON, GIANT_COD, ONE_EYED_OWL;
don't stack different types into one variable and please generify the EntityType. Example:
`public static RegistryObject<EntityType<BoatEntity>> BOAT_ENTITY;`

2022-08-30 09:14 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/registry/TensuraRegistry.java
> +        ItemRegistry.register(ITEMS); //Register Items to our Registry (wtf)
??

2022-08-30 09:17 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/registry/TensuraRegistry.java
> +        ItemRegistry.register(ITEMS); //Register Items to our Registry (wtf)
lol sometime it just doesnt import ITEMS, dunno why, I had to keep retype the line everytime I touched ItemRegistry

2022-08-30 17:23 UTC, Charismara requested changes

2022-08-30 17:23 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/custom/AntiMagicMaskItem.java
> +        super(material, slot, new Properties()
Please set the Material and EquipmentSlot in the super statement and remove the constructor params

2022-08-30 17:23 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/custom/IceBladeItem.java
> +        super(pTier, pAttackDamageModifier, pAttackSpeedModifier,
you could set the tier and int in the super statement and move the constructor params

2022-08-30 17:23 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/registry/TensuraEntityTypes.java
>      public static RegistryObject<EntityType> GIANT_SALMON, GIANT_COD, ONE_EYED_OWL;
Please do the same for the SALMON, COD and OWL

2022-08-31 10:47 UTC, Charismara approved these changes

2022-08-31 10:47 UTC, merged