No-model Kiln Block
ManasMods/reincarnated_mod pull request #507
Opened 2022-09-07 13:15 UTC by minheragon12345

2022-09-08 07:29 UTC, Charismara commented
please add the `runServer` folder to the git ignore file and remove it from the repo

2022-09-08 08:44 UTC, Charismara requested changes

2022-09-08 08:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/block/KilnBlock.java
> +                ((KilnBlockEntity) blockEntity).drops();
since we're in a java 16+ we can use

```java
 if (blockEntity instanceof KilnBlockEntity kilnBlockEntity) {
                kilnBlockEntity.drops();
}
```
instead of casting the object

2022-09-08 08:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/block/KilnBlock.java
> +            if(entity instanceof KilnBlockEntity) {
please use `entity instanceof KilnBlockEntity kilnBlockEntity` instead of casting the class

2022-09-08 08:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/blockentity/KilnBlockEntity.java
> +    }
change `label.tensura.kiln` to `tensura.kiln.label`

2022-09-08 08:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/blockentity/KilnBlockEntity.java
> +    public int goldProgress = 0;
do we need 3 fields? i thought they can not be used at the same time

2022-09-08 08:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/blockentity/KilnBlockEntity.java
> +    private int maxMoltenProgress = 144;
if that value doesn't change, make it final

2022-09-08 08:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/network/play2server/RequestKilnMixingLeft.java
> +@RequiredArgsConstructor
`RequiredArgsConstructor` with no fields. Please use `NoArgsConstructor` instead

2022-09-08 08:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/network/play2server/RequestKilnMixingRight.java
> +@RequiredArgsConstructor
`RequiredArgsConstructor` with no fields. Please use `NoArgsConstructor` instead

2022-09-08 08:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/network/play2server/RequestKilnOuputMagisteel.java
> +@RequiredArgsConstructor
`RequiredArgsConstructor` with no fields. Please use `NoArgsConstructor` instead

2022-09-08 08:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/network/play2server/RequestKilnOuputMolten.java
> +@RequiredArgsConstructor
`RequiredArgsConstructor` with no fields. Please use `NoArgsConstructor` instead

2022-09-08 08:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/registry/TensuraMenuTypes.java
> +            DeferredRegister.create(ForgeRegistries.CONTAINERS, Tensura.MOD_ID);
please move the registry holder to `TensuraRegistry`

2022-09-08 08:53 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/blockentity/KilnBlockEntity.java
> +    public int goldProgress = 0;
I need to check if the other two is 0 when one is in

2022-09-08 19:00 UTC, Charismara requested changes

2022-09-08 19:00 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/util/TensuraTags.java
> +        public static TagKey<Item> GOLD_MOLTEN = forgeTag("molten/gold");
are molten materials items?

2022-09-08 22:43 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/util/TensuraTags.java
> +        public static TagKey<Item> GOLD_MOLTEN = forgeTag("molten/gold");
Both ores and ingots

2022-09-08 22:50 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/util/TensuraTags.java
> +        public static TagKey<Item> GOLD_MOLTEN = forgeTag("molten/gold");
Modpack makers can add more too cus it's forge Tag

2022-09-09 07:15 UTC, Charismara requested changes

2022-09-09 07:15 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/block/KilnBlock.java
> +                }
wouldn't it make more sense to return the `KilnPart.BASE` menu when using the other side too?

2022-09-09 07:15 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/blockentity/KilnBlockEntity.java
> +        };
please move this field above the constructor. Where is it used anyway?

2022-09-09 07:15 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/blockentity/KilnBlockEntity.java
> +        if (!this.remove && facing != null && capability == net.minecraftforge.items.CapabilityItemHandler.ITEM_HANDLER_CAPABILITY) {
why aren't you importing the classes instead of writing their classpath?

2022-09-09 07:15 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/blockentity/KilnBlockEntity.java
> +        this.handlers = net.minecraftforge.items.wrapper.SidedInvWrapper.create(this, Direction.UP, Direction.DOWN, Direction.NORTH);
why aren't you importing the class instead of writing the classpath?

2022-09-09 07:17 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/block/KilnBlock.java
> +                }
the kiln has two parts, that's cool
but that makes it 2 blocks, so the TOP part has a separate inv too

2022-09-09 07:18 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/blockentity/KilnBlockEntity.java
> +        if (!this.remove && facing != null && capability == net.minecraftforge.items.CapabilityItemHandler.ITEM_HANDLER_CAPABILITY) {
lmao I copied the furnace code, didnt think much there

2022-09-09 07:22 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/blockentity/KilnBlockEntity.java
> +        };
it's mainly used in Menu

2022-09-09 07:24 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/util/TensuraTags.java
> +        public static TagKey<Item> GOLD_MOLTEN = forgeTag("molten/gold");
I see I might need help doing that tho, cus I don't understand wut u saying lmao

2022-09-09 10:30 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/blockentity/KilnBlockEntity.java
> +    public int goldProgress = 0;
this will need more discussion

2022-09-09 10:30 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/network/play2server/RequestKilnMixingLeft.java
> +}
I dont know enum :(

2022-09-09 21:07 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/block/KilnBlock.java
> +                }
you could just make the top part returning the inventory/blockentity of the bottom part

2022-09-09 21:08 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/blockentity/KilnBlockEntity.java
> +        };
couldn't u use the blockentity instead?

2022-09-09 21:18 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/network/play2server/RequestKilnMixingLeft.java
> +}
https://www.w3schools.com/java/java_enums.asp

2022-09-10 07:53 UTC, Charismara requested changes

2022-09-10 07:53 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/screen/KilnScreen.java
> +
No static import please. they lead to some weird problems

2022-09-18 17:08 UTC, Charismara commented
I thought a bit more about this and we probably really want another way of processing the stuff instead of 5 different recipes. First conzept i got in mind:

# Molten Material
A simple, data-driven, object which servers as conversion type from one (or more items) into a processable state.

```java
//example structure
ResourceLocation materialTypeId
int renderColor; //Can be used to render the materials in different colors
```

# Smelt
Smelting a single Item into their **Molten Material** form.

```java
//example structure
ItemStack inputStack;
ResourceLocation outputMaterialTypeId;
int moltenMaterialAmount;
```

# Cast
Casting a single the **Molten Material** into their solid version (which version is selectable in the gui, nugget, ingot, block). 
```java
//example structure
ResourceLocation inputMaterialTypeId;
int moltenMaterialAmount;
ItemStack outputStack
```

# Refine
Casting two **Molten Material**s into a single & new solid version (which version is selectable in the gui, nugget, ingot, block).
```java
//example structure
ResourceLocation inputMaterialTypeId1;
int moltenMaterialAmount1;
ResourceLocation inputMaterialTypeId2;
int moltenMaterialAmount2;
ItemStack outputStack
```

# Advantages
- reduced recipe amount to 3
- enhanced look of the molten version due to different colors
- full customization due to 100% data driven objects

@minheragon12345 What do u think?

2022-09-18 17:17 UTC, minheragon12345 commented
> I thought a bit more about this and we probably really want another way of processing the stuff instead of 5 different recipes. First conzept i got in mind:
> 
> # Molten Material
> A simple, data-driven, object which serves as conversion type from one (or more items) into a processable state.
> 
> ```java
> //example structure
> ResourceLocation materialTypeId
> int renderColor; //Can be used to render the materials in different colors
> ```
> 
> # Smelt
> Smelting a single Item into their **Molten Material** form.
> 
> ```java
> //example structure
> ItemStack inputStack;
> ResourceLocation outputMaterialTypeId;
> int moltenMaterialAmount;
> ```
> 
> # Cast
> Casting a single the **Molten Material** into their solid version (which version is selectable in the gui, nugget, ingot, block).
> 
> ```java
> //example structure
> ResourceLocation inputMaterialTypeId;
> int moltenMaterialAmount;
> ItemStack outputStack
> ```
> 
> # Refine
> Casting two **Molten Material**s into a single & new solid version (which version is selectable in the gui, nugget, ingot, block).
> 
> ```java
> //example structure
> ResourceLocation inputMaterialTypeId1;
> int moltenMaterialAmount1;
> ResourceLocation inputMaterialTypeId2;
> int moltenMaterialAmount2;
> ItemStack outputStack
> ```
> 
> # Advantages
> * reduced recipe amount to 3
> * enhanced look of the molten version due to different colors
> * full customization due to 100% data driven objects
> 
> @minheragon12345 What do u think?

2022-09-18 17:18 UTC, minheragon12345 commented
Miscliked, oof...
Yeh, it sounds amazing! I'm willing to spend more time for the best quality.

2022-09-22 17:26 UTC, Charismara commented
Things we need to fix/check

- [ ] Fix Mixing Slot Item get's droppen when breaking the block
- [ ] Allow users to hopper Items into the melting input slot
- [ ] Allow users to hopper fuel into to fuel slot
- [ ] Allow users to hopper mixing items out of the mixing slot
- [ ] Allow to quick craft items
- [ ] Add JEI Plugin for melting recipes
- [ ] Add JEI Plugin for mixing recipes

2022-10-07 12:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ManasMods/reincarnated_mod?pullRequest=507) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ManasMods/reincarnated_mod?pullRequest=507) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Charismara<br/>:x: minheragon12345<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ManasMods/reincarnated_mod?pullRequest=507) it.</sub>

2022-10-22 20:02 UTC, Nieadni commented
I dont really get what was happening here. The Kiln fully works in Smithing, well atleast its placeable, the GUI works and has a good sound when placing. Havent tested if it smelts stuff

2022-10-23 14:21 UTC, Charismara approved these changes

2022-10-23 14:24 UTC, merged