Dev/lazuline
ManasMods/reincarnated_mod pull request #593
Opened 2022-12-05 14:54 UTC by AbyssDweller

#529 (remove like flames music disk and its .ogg ) done
#528 (remove cooking pot) done
#544 parts are done

2022-12-05 14:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ManasMods/reincarnated_mod?pullRequest=593) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ManasMods/reincarnated_mod?pullRequest=593) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ManasMods/reincarnated_mod?pullRequest=593) it.</sub>

2022-12-11 17:01 UTC, Charismara requested changes
please also remove the `like_flames` entry in the sounds.json file

2022-12-11 17:08 UTC, AbyssDweller commented on src/main/java/com/github/manasmods/tensura/data/gen/TensuraRecipeProvider.java
> +                .save(consumer);
its already at 4, idk why the indents are like that 
![image](https://user-images.githubusercontent.com/80689879/206917857-94363f29-24e3-42b5-8e68-71578dd412c3.png)

2022-12-11 17:18 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/data/gen/TensuraRecipeProvider.java
> +                .save(consumer);
hmm try changing the continuation indent to 4 too

2022-12-11 17:25 UTC, Charismara commented
There are still some Cooking Pot things:

- [ ] TensuraBlockLoot.java:66
- [ ] TensuraBlocks.java:30
- [ ] TensuraBlockTagProvider.java:82
- [ ] TensuraBlockTagProvider.java:128

please remove them too

2022-12-11 17:28 UTC, Charismara commented on src/main/resources/assets/tensura/sounds.json
>      ]
Those lines need to be remove too. The remaining file is basically just the empty json object (due to the fact that we don't have any other sound yet)

2022-12-11 17:30 UTC, AbyssDweller commented on src/main/resources/assets/tensura/sounds.json
>      ]
yep, I forgot to push that one when I noticed that a couple minutes ago

2022-12-11 18:41 UTC, Charismara approved these changes
looks good to me. let's see that the pipeline says

2022-12-11 18:51 UTC, merged