Weapons
ManasMods/reincarnated_mod pull request #612
Opened 2023-01-01 12:39 UTC by minheragon12345

2023-01-02 08:58 UTC, Charismara requested changes

2023-01-02 08:58 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/entity/projectile/SevererBladeProjectile.java
> +import net.minecraft.world.entity.*;
No * imports

2023-01-02 08:58 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/registry/items/TensuraToolItems.java
> +import com.github.manasmods.tensura.item.templates.*;
don't use star imports please

2023-01-23 15:44 UTC, Charismara requested changes

2023-01-23 15:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/data/recipe/SmithingBenchRecipe.java
> +            })
That thing looks terrible.

use `item.getClass() == SwordItem.class` instead

2023-01-23 15:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/handler/ClientEventHandler.java
> +    }
This is unsafe. Please use the reach attribute for it

2023-01-23 15:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/handler/WeaponAttackHandler.java
> +}
There should be a way to do this in the Item class

2023-01-23 15:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/custom/DragonKnucklesItem.java
> +    }
use early out pattern for better readability

2023-01-23 15:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/custom/DragonKnucklesItem.java
> +        }
extract this into private methods

2023-01-23 15:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/custom/SpatialBladeItem.java
> +    private final List<Enchantment> enchantmentList = ImmutableSet.of(Enchantments.PIERCING, Enchantments.IMPALING, Enchantments.CHANNELING).asList();
this can be static

2023-01-23 15:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/SimpleGreatSwordItem.java
> +    }
use lombok getter for those

2023-01-23 15:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/SimpleKatanaItem.java
> +    }
use lombok getters instead

2023-01-23 15:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/SimpleLongSwordItem.java
> +    }
use lombok getters instead

2023-01-23 15:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/SimpleOdachiItem.java
> +    }
use lombok getters instead

2023-01-23 15:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/SimpleTachiItem.java
> +    }
use lombok getters instead

2023-01-23 15:44 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/network/play2server/PacketLongWeaponAttack.java
> +}
Easy way to hit any entity from any distance with what ever the player has in his main hand.

Unsafe. Never trust a client!

2023-02-01 17:25 UTC, Charismara requested changes

2023-02-01 17:25 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/handler/WeaponAttackHandler.java
> +    }
pretty sure there should be a way to do this in the item classes instead

2023-02-01 17:25 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/handler/WeaponAttackHandler.java
> +    }
please do that in the item class

2023-02-01 17:25 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/custom/DragonKnucklesItem.java
> +                || ToolActions.SHEARS_CARVE.equals(toolAction);
use early out pattern for better readability

2023-02-01 17:25 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/custom/SimpleGreatSwordItem.java
> +            builder.put(ForgeMod.ATTACK_RANGE.get(), new AttributeModifier("Weapon Range modifier", this.getCurrentAttackRange(), AttributeModifier.Operation.ADDITION));
missing UUID

2023-02-01 17:25 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/custom/SimpleGreatSwordItem.java
> +        super.inventoryTick(pStack, pLevel, pEntity, pSlotId, pIsSelected);
What are you doing here?

2023-02-01 17:25 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/custom/SpatialBladeItem.java
> +        if (!worldIn.isClientSide && tag != null && tag.getInt("attackMode") == 0) {
Is there no boolean for the attack mode?

2023-02-02 16:12 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/handler/WeaponAttackHandler.java
> +                && player.distanceTo(e.getEntity()) > ForgeMod.ATTACK_RANGE.get().getDefaultValue() - 0.75f) {
making the addition range value to negative doesnt seem to work for me.

2023-02-02 16:17 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/item/custom/SimpleGreatSwordItem.java
> +        super.inventoryTick(pStack, pLevel, pEntity, pSlotId, pIsSelected);
To get the Offhand thingy and actual changing in the tool tips if Im not correctly

2023-02-02 16:32 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/custom/SimpleGreatSwordItem.java
> +        super.inventoryTick(pStack, pLevel, pEntity, pSlotId, pIsSelected);
offhand thingy?

2023-02-02 17:43 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/item/custom/SimpleGreatSwordItem.java
> +            builder.put(ForgeMod.ATTACK_RANGE.get(), new AttributeModifier("Weapon Range modifier", this.getCurrentAttackRange(), AttributeModifier.Operation.ADDITION));
wut is it for?

2023-02-02 17:55 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/handler/WeaponAttackHandler.java
> +    }
check the coder discord group chat, cant :(

2023-02-02 17:55 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/handler/WeaponAttackHandler.java
> +    }
check the coder discord group chat, cant :(

2023-02-02 17:55 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/item/custom/SpatialBladeItem.java
> +        if (!worldIn.isClientSide && tag != null && tag.getInt("attackMode") == 0) {
can u explain it more

2023-02-03 07:07 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/custom/SimpleGreatSwordItem.java
> +            builder.put(ForgeMod.ATTACK_RANGE.get(), new AttributeModifier("Weapon Range modifier", this.getCurrentAttackRange(), AttributeModifier.Operation.ADDITION));
to ensure no one accidentally overwrites our attribute modifier

2023-02-03 07:11 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/custom/SpatialBladeItem.java
> +        if (!worldIn.isClientSide && tag != null && tag.getInt("attackMode") == 0) {
you could just use a boolean instead of an int which is better for memory management since there are only 2 attack modes (0 and 1)

2023-02-03 18:04 UTC, Charismara requested changes

2023-02-03 18:04 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/LongTwoHandedItem.java
> +        }
Is there a way to do this without the tick method? They are always so expensive

2023-02-03 18:04 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/SmithingSchematicItem.java
> +                .rarity(Rarity.create("Schematic", ChatFormatting.GREEN)));
Please create custom Rarities in a separate class

2023-02-04 09:34 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/item/templates/LongTwoHandedItem.java
> +        }
Yeh, I tried but the getAttributeModifiers method only supports Equipement Slot and Item Stack
we need to get the entity to check for the user's offhand
<img width="813" alt="image" src="https://user-images.githubusercontent.com/29400456/216760022-6a229252-b89e-4de1-93f5-a8f44b8c13e4.png">

2023-02-04 10:03 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/LongTwoHandedItem.java
> +        }
what about `itemStack#getEquipmentSlot()`?

2023-02-19 11:19 UTC, Charismara requested changes

2023-02-19 11:19 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/custom/IceBladeItem.java
>          if (Screen.hasShiftDown()) {
This will crash servers since `Screen` is a client only class. use the `pIsAdvanced` instead

2023-02-19 11:19 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/custom/SpatialBladeItem.java
>          if (Screen.hasShiftDown()) {
This will crash servers since `Screen` is a client only class. use the `pIsAdvanced` instead

2023-02-19 11:19 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/custom/SimpleKatanaItem.java
> +                        .put(ManasCoreAttributes.CRIT_CHANCE.get(), new AttributeModifier(UUID.fromString("6595a9a4-a3b0-11ed-a8fc-0242ac120002"),
extract uuid into a protected static final variable

2023-02-19 11:19 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/custom/SimpleKatanaItem.java
> +                    .put(ManasCoreAttributes.CRIT_CHANCE.get(), new AttributeModifier(UUID.fromString("6595a9a4-a3b0-11ed-a8fc-0242ac120002"),
extract uuid into a protected static final variable

2023-02-19 11:19 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/custom/SimpleKodachiItem.java
> +                    .put(ForgeMod.ATTACK_RANGE.get(), new AttributeModifier(UUID.fromString("60882508-a398-11ed-a8fc-0242ac120002"),
extract uuid into a protected static final variable

2023-02-19 11:19 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/custom/SimpleKodachiItem.java
> +                    .put(ManasCoreAttributes.CRIT_MULTIPLIER.get(), new AttributeModifier(UUID.fromString("e731da6e-a3b0-11ed-a8fc-0242ac120002"),
extract uuid into a protected static final variable

2023-02-19 11:19 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/custom/SimpleKodachiItem.java
> +                    .put(ManasCoreAttributes.CRIT_CHANCE.get(), new AttributeModifier(UUID.fromString("6595a9a4-a3b0-11ed-a8fc-0242ac120002"),
extract uuid into a protected static final variable

2023-02-19 11:19 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/custom/SimpleLongSwordItem.java
> +                    .put(ForgeMod.ATTACK_RANGE.get(), new AttributeModifier(UUID.fromString("60882508-a398-11ed-a8fc-0242ac120002"),
extract uuid into a protected static final variable

2023-02-19 11:19 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/custom/SimpleOdachiItem.java
> +                        .put(ManasCoreAttributes.CRIT_CHANCE.get(), new AttributeModifier(UUID.fromString("6595a9a4-a3b0-11ed-a8fc-0242ac120002"),
extract uuid into a protected static final variable

2023-02-19 11:19 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/custom/SimpleOdachiItem.java
> +                    .put(ManasCoreAttributes.CRIT_CHANCE.get(), new AttributeModifier(UUID.fromString("6595a9a4-a3b0-11ed-a8fc-0242ac120002"),
extract uuid into a protected static final variable

2023-02-19 11:19 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/custom/SimpleShortSwordItem.java
> +                .put(ForgeMod.ATTACK_RANGE.get(), new AttributeModifier(UUID.fromString("60882508-a398-11ed-a8fc-0242ac120002"),
extract uuid into a protected static final variable

2023-02-19 11:19 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/custom/SimpleShortSwordItem.java
> +                .put(ManasCoreAttributes.CRIT_MULTIPLIER.get(), new AttributeModifier(UUID.fromString("e731da6e-a3b0-11ed-a8fc-0242ac120002"),
extract uuid into a protected static final variable

2023-02-19 11:19 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/custom/SimpleSpearItem.java
> +                    .put(ForgeMod.ATTACK_RANGE.get(), new AttributeModifier(UUID.fromString("60882508-a398-11ed-a8fc-0242ac120002"),
extract uuid into a protected static final variable

2023-02-19 11:19 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/custom/SimpleTachiItem.java
> +                        .put(ManasCoreAttributes.CRIT_CHANCE.get(), new AttributeModifier(UUID.fromString("6595a9a4-a3b0-11ed-a8fc-0242ac120002"),
extract uuid into a protected static final variable

2023-02-19 11:19 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/custom/SimpleTachiItem.java
> +                    .put(ManasCoreAttributes.CRIT_CHANCE.get(), new AttributeModifier(UUID.fromString("6595a9a4-a3b0-11ed-a8fc-0242ac120002"),
extract uuid into a protected static final variable

2023-02-20 01:13 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/item/custom/SpatialBladeItem.java
>          if (Screen.hasShiftDown()) {
Wdym? Can I do sth similar like check pressing shift with pIsAdvanced?

2023-02-20 01:38 UTC, minheragon12345 commented on src/main/java/com/github/manasmods/tensura/item/custom/IceBladeItem.java
>          if (Screen.hasShiftDown()) {
<img width="509" alt="image" src="https://user-images.githubusercontent.com/29400456/219989999-bf5b438b-7835-4e9e-8dab-388bb1a51a76.png">
I tested and it works fine in server tho...

2023-02-21 07:27 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/custom/IceBladeItem.java
>          if (Screen.hasShiftDown()) {
`Screen` is only pesent on client side. please do not use those side only classes / methods in classes which get used on both sides

2023-02-21 07:30 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/custom/SpatialBladeItem.java
>          if (Screen.hasShiftDown()) {
the `pIsAdvanced` should ether be the var to check for F3 + H tooltips or the shift thing. In case it's the F3 + H tooltip thing then use a DistExecutor to get the Screen value savely

2023-02-28 16:29 UTC, Charismara requested changes

2023-02-28 16:29 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/custom/SimpleKatanaItem.java
> +        return super.onEntitySwing(stack, pEntity);
please use early out pattern for your if statements

2023-02-28 16:29 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/custom/TwoHandedLongSword.java
> +        return super.onEntitySwing(stack, pEntity);
please use early out pattern for your if statements

2023-02-28 19:07 UTC, Charismara requested changes

2023-02-28 19:07 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/custom/SimpleKatanaItem.java
> +                    || !((ArmorStand) livingentity).isMarker()) && entity.canHit(livingentity, 2)) {
please use early out patter instead of combining conditions

2023-02-28 19:07 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/custom/TwoHandedLongSword.java
> +                    || !((ArmorStand) livingentity).isMarker()) && entity.canHit(livingentity, 1 + attackRange)) {
please use early out patter instead of combining conditions

2023-02-28 19:30 UTC, Charismara requested changes

2023-02-28 19:30 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/custom/SimpleKatanaItem.java
> +            if (livingentity instanceof ArmorStand armorStand && armorStand.isMarker()) break;
use `continue` instead of break

2023-02-28 19:30 UTC, Charismara commented on src/main/java/com/github/manasmods/tensura/item/templates/custom/TwoHandedLongSword.java
> +            if (livingentity instanceof ArmorStand armorStand && armorStand.isMarker()) break;
use `continue` instead of break

2023-02-28 19:34 UTC, Charismara approved these changes
another 6.5k lines of code which get merged into Tensura. 

Good Job!

2023-02-28 19:35 UTC, merged